added applied intuition
coderQuad/New-Grad-Positions-2023 pull request #147
Opened 2022-07-02 04:23 UTC by samihan123

2022-07-02 18:08 UTC, KnlnKS requested changes

2022-07-02 18:08 UTC, KnlnKS commented on README.md
> +| [Applied Intution](https://jobs.lever.co/applied/cbcfe9b0-7f94-4dee-aa27-248e4135c307) | MOUNTAIN VIEW, CA | New Grad, Software Engineer |
```suggestion
| [Applied Intuition](https://jobs.lever.co/applied/cbcfe9b0-7f94-4dee-aa27-248e4135c307) | MOUNTAIN VIEW, CA | New Grad, Software Engineer |
```
Typo

2022-07-02 20:22 UTC, KnlnKS commented
Also consider linking this: https://jobs.lever.co/applied/?team=New%20Grad. As there are more than just one New Grad role.

2022-07-02 21:51 UTC, samihan123 commented
Done

2022-07-03 04:27 UTC, jameszhang-a approved these changes

2022-07-06 04:05 UTC, merged